name: Build and Release CW Plugin

on:
  push:
    branches:
      - '**'
  release:
    types: [published, prereleased]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install SDK
        run: |
          pip install ./class-widgets-sdk-master

      - name: Create dist directory
        run: mkdir -p dist

      - name: Package Plugin
        run: |
          # Use the SDK tool to package the plugin
          cw-plugin-pack ./net.bloret.launcher -o ./dist/net.bloret.launcher.cwplugin

      - name: Create Release
        uses: softprops/action-gh-release@v2
        if: github.event_name == 'release'
        with:
          files: dist/net.bloret.launcher.cwplugin
          tag_name: ${{ github.event.release.tag_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: net.bloret.launcher.cwplugin
          path: dist/net.bloret.launcher.cwplugin
